# Generated by Django 2.2.5 on 2020-09-21 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='maker',
            new_name='organizer',
        ),
    ]
